
---

- hosts: all
  become: true
  gather_facts: true     ##lock/unlock if needed.
  tasks:

  - name: Install apache and php for Ubuntu servers
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Install httpd and php for Rocky servers
    dnf:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == "RedHat"

...
